#springdoc:
#  swagger-ui:
#    path: /swagger-ui/index.html
##    localhost:8080/api-docs
#  api-docs:
#    path: /swagger-doc

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: POC


#server:
#  port: 8080
