#springdoc:
#  swagger-ui:
#    path: /swagger-doc/swagger-ui.html
#  api-docs:
#    path: /swagger-doc/v3/api-docs

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: POC

