// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:string):Promise<boolean>;

export function GetData():Promise<Array<main.Todo>>;

export function GetOne(arg1:number):Promise<string>;

export function Update(arg1:number,arg2:string):Promise<boolean>;
