// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['Todo']['Add'](arg1);
}

export function GetData() {
  return window['go']['main']['Todo']['GetData']();
}

export function GetOne(arg1) {
  return window['go']['main']['Todo']['GetOne'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['main']['Todo']['Update'](arg1, arg2);
}
